In [ ]:
import numpy as np

In [ ]:
m=200
n=3

In [ ]:
tv=np.random.uniform(10,200,(200,1))
radio=np.random.uniform(10,100,(200,1))
newspaper=np.random.uniform(10,150,(200,1))

In [ ]:
tv[:5]

array([[ 39.64354168],
       [ 39.63895886],
       [ 21.03588631],
       [174.5734677 ],
       [124.21185223]])

In [ ]:
newspaper[:5]

array([[ 54.80694414],
       [135.37325199],
       [ 64.48823502],
       [ 11.51727121],
       [136.7534767 ]])

In [ ]:
radio[:5]

array([[64.57861537],
       [10.82773465],
       [19.13243886],
       [69.71515922],
       [10.45554255]])

In [ ]:
X=np.c_[tv,newspaper,radio]

In [ ]:
X.shape

(200, 3)

In [ ]:
X[:5]

array([[ 39.64354168,  54.80694414,  64.57861537],
       [ 39.63895886, 135.37325199,  10.82773465],
       [ 21.03588631,  64.48823502,  19.13243886],
       [174.5734677 ,  11.51727121,  69.71515922],
       [124.21185223, 136.7534767 ,  10.45554255]])

In [ ]:
y = 1 + 4 * tv + 3 * newspaper + 2 * radio + np.random.randn(200, 1)

In [ ]:
y.shape

(200, 1)

In [ ]:
y[:5]

array([[453.04519955],
       [586.29581839],
       [316.31947873],
       [872.07812496],
       [930.98364925]])

# Custom Linear Regression

In [ ]:
from sklearn.base import BaseEstimator,TransformerMixin

In [ ]:
class MyLinearRegression(BaseEstimator,TransformerMixin):
  def __init__(self,**kwargs):
    pass
  def fit(self,X,y):
    X_b=np.c_[np.ones((len(X),1)),X]
    self.theta_best=np.linalg.inv(X_b.T @ X_b)@X_b.T@y
    self.intercept=self.theta_best[0]
    self.coefficient=self.theta_best[1:]
    return self
  def predict(self,X):
     X_b=np.c_[np.ones((len(X),1)),X]
     y_pred=X_b@self.theta_best
     return y_pred

In [ ]:
custom_lin_reg=MyLinearRegression()

In [ ]:
custom_lin_reg.fit(X,y)


MyLinearRegression()

In [ ]:
custom_lin_reg.theta_best

array([[1.53681362],
       [3.99733572],
       [2.99934928],
       [1.99543726]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg=LinearRegression()

In [ ]:
lin_reg.fit(X,y)

LinearRegression()

In [ ]:
lin_reg.intercept_

array([1.53681362])

In [ ]:
lin_reg.coef_

array([[3.99733572, 2.99934928, 1.99543726]])

In [ ]:
y[:5]

array([[453.04519955],
       [586.29581839],
       [316.31947873],
       [872.07812496],
       [930.98364925]])

In [ ]:
lin_reg.predict(X[:5])

array([[453.25310311],
       [587.62477117],
       [317.22463626],
       [873.02211811],
       [929.08810905]])

In [ ]:
custom_lin_reg.predict(X[:5])

array([[453.25310311],
       [587.62477117],
       [317.22463626],
       [873.02211811],
       [929.08810905]])

# Custom BGD

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
class CustomBGDRegressor(BaseEstimator, TransformerMixin):
    def __init__(self, eta=0.1, n_iterations=1000, random_state=42):
        self.eta = eta
        self.n_iterations = n_iterations
        self.random_state = random_state
        np.random.seed(self.random_state)
    def fit(self, X_scaled, y):
        m, n = X_scaled.shape
        X_b = np.c_[np.ones((len(X_scaled), 1)), X_scaled]
        self.theta = np.random.randn(n + 1, 1)
        for iteration in range(self.n_iterations):
            gradients = 2 / m * X_b.T @ (X_b @ self.theta - y)
            self.theta = self.theta - self.eta * gradients
        return self
    def predict(self, X_scaled):
        X_b = np.c_[np.ones((len(X_scaled), 1)), X_scaled]
        y_pred = X_b @ self.theta
        return y_pred

In [ ]:
custom_bgd=CustomBGDRegressor()

In [ ]:
custom_bgd.fit(X_scaled,y)

CustomBGDRegressor()

In [ ]:
custom_bgd.theta

array([[762.05603197],
       [224.38928538],
       [128.92370842],
       [ 52.41649733]])

In [ ]:
lin_reg_1=LinearRegression()

In [ ]:
lin_reg_1.fit(X_scaled,y)

LinearRegression()

In [ ]:
lin_reg_1.intercept_

array([762.05603197])

In [ ]:
lin_reg_1.coef_

array([[224.38928538, 128.92370842,  52.41649733]])

In [ ]:
y[:5]

array([[453.04519955],
       [586.29581839],
       [316.31947873],
       [872.07812496],
       [930.98364925]])

In [ ]:
custom_bgd.predict(X_scaled[:5])

array([[453.25310311],
       [587.62477117],
       [317.22463626],
       [873.02211811],
       [929.08810905]])

In [ ]:
lin_reg_1.predict(X_scaled[:5])

array([[453.25310311],
       [587.62477117],
       [317.22463626],
       [873.02211811],
       [929.08810905]])

# Custom SGD

In [ ]:
class CustomSGDRegressor(BaseEstimator, TransformerMixin):
    def __init__(self, eta=0.1, n_iterations=1000, random_state=42):
        self.eta = eta
        self.n_iterations = n_iterations
        self.random_state = random_state
        np.random.seed(self.random_state)
    def fit(self, X_scaled, y):
        m, n = X_scaled.shape
        X_b = np.c_[np.ones((len(X_scaled), 1)), X_scaled]
        self.theta = np.random.randn(n + 1, 1)
        for iteration in range(self.n_iterations):
           for i in range(m):
              X_i=X_b[i:i+1]
              y_i=y[i:i+1]
              gradients = 2 * X_i.T @ (X_i @ self.theta - y_i)
              self.theta = self.theta - self.eta * gradients
        return self
    def predict(self, X_scaled):
        X_b = np.c_[np.ones((len(X_scaled), 1)), X_scaled]
        y_pred = X_b @ self.theta
        return y_pred

In [ ]:
custom_SGD=CustomSGDRegressor()

In [ ]:
custom_SGD.fit(X_scaled,y)

CustomSGDRegressor()

In [ ]:
custom_SGD.theta

array([[761.78304896],
       [223.99363316],
       [128.17195801],
       [ 52.31095875]])

In [ ]:
y[:5]

array([[453.04519955],
       [586.29581839],
       [316.31947873],
       [872.07812496],
       [930.98364925]])

In [ ]:
custom_SGD.predict(X_scaled[:5])

array([[453.84896054],
       [587.02758397],
       [317.9649188 ],
       [873.40341487],
       [927.8721863 ]])